PYDISCORD_VERSION_MAJOR = 0
PYDISCORD_VERSION_MINOR = 1
PYDISCORD_VERSION_REVISION = 2
PYDISCORD_VERSION_STR = str(PYDISCORD_VERSION_MAJOR) + str(PYDISCORD_VERSION_MINOR) + str(PYDISCORD_VERSION_REVISION)
